name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run unit tests
        run: yarn test

      - name: Package
        run: yarn pack

  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint
