name: Release Package

on:
  release:
    types: [published]

# Configure permissions so that the action is only allowed to read the code
permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn build

      - name: Publish
        run: yarn npm publish --access public
