name: Publish

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to package index
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Setup .yarnrc.yml
        run: |
          cat <<'EOF' >> .yarnrc.yml
          npmScopes:
            factset:
              npmRegistryServer: "https://${{ secrets.NPM_PUBLISH_URL }}"
              npmPublishRegistry: "https://${{ secrets.NPM_PUBLISH_URL }}"
              npmAlwaysAuth: true
          npmRegistries:
            "//${{ secrets.NPM_PUBLISH_URL }}":
              npmAuthToken: "${{ secrets.NPM_AUTH_TOKEN }}"
              npmAlwaysAuth: true
          EOF

      - name: Install dependencies
        run: |
          yarn install

      - name: Build package
        run: |
          yarn build

      - name: Publish
        run: |
          yarn npm publish --access public
